os: linux

language: java

jdk: oraclejdk8

addons:
 apt:
  packages:
   - oracle-java8-installer

install: true
  
script:
 - tools/build_dependencies.sh $TRAVIS_BUILD_DIR/dependencies $TRAVIS_BUILD_DIR/m2
 - mvn clean install -Dmaven.repo.local=$TRAVIS_BUILD_DIR/m2
